/* Integración reutilizable: cargar dashboard.js (monitorReady) antes de este script. */
'use strict';
(async()=>{
 const scriptUrl=new URL(document.currentScript?.src || '/frontend/components/chatbot.js',location.href);
 const ready=await window.monitorReady; if(!ready)return;
 const {user,context,api}=ready;
 const link=document.createElement('link');link.rel='stylesheet';link.href=new URL('../css/chatbot.css',scriptUrl).href;document.head.append(link);
 const avatarUrl=new URL('../assets/img/chatbot-monitor.png',scriptUrl).href;
 const host=document.createElement('div');host.id='monitor-chat-root';host.innerHTML=`
 <button class="chat-launch" id="chat-launch" aria-label="Abrir asistente Monitor IA" aria-haspopup="dialog" aria-expanded="false"><img class="chat-avatar" src="${avatarUrl}" alt="" /></button>
 <div class="chat-backdrop" id="chat-backdrop" hidden></div>
 <section class="chat-panel" id="chat-panel" role="dialog" aria-modal="true" aria-labelledby="chat-name" hidden>
 <header class="chat-header"><div class="chat-title"><img class="chat-avatar chat-header-avatar" src="${avatarUrl}" alt="" /><div><strong id="chat-name">Asistente IA</strong><small id="chat-provider"></small></div></div><div class="chat-actions"><button class="icon-btn" id="chat-new" aria-label="Nueva conversación" title="Nueva conversación">＋</button><button class="icon-btn" id="chat-expand" aria-label="Expandir pantalla" aria-pressed="false" title="Expandir">⛶</button><button class="icon-btn" id="chat-close" aria-label="Cerrar asistente" title="Cerrar">×</button></div></header>
 <div class="chat-filters"><select id="chat-course" aria-label="Filtrar curso"><option value="">Todos mis cursos</option></select><select id="chat-student" aria-label="Filtrar estudiante"><option value="">Mi ámbito completo</option></select></div>
 <div class="chat-feed" id="chat-feed"><div class="chat-content"><div class="chat-welcome" id="chat-welcome"><img class="chat-welcome-avatar" src="${avatarUrl}" alt="Robot Monitor IA" /><h2 id="chat-greeting"></h2><p class="chat-question">¿En qué puedo ayudarte?</p><div class="suggestions"><button class="suggestion" data-question="¿Cuál es mi porcentaje de asistencia?"><span aria-hidden="true">◕</span> ¿Cuál es mi porcentaje de asistencia?</button><button class="suggestion" data-question="¿Cuántas faltas tengo?"><span aria-hidden="true">♙</span> ¿Cuántas faltas tengo?</button><button class="suggestion" data-question="¿Cuántas tardanzas tengo?"><span aria-hidden="true">◷</span> ¿Cuántas tardanzas tengo?</button><button class="suggestion" data-question="Muéstrame mis cursos"><span aria-hidden="true">▣</span> Muéstrame mis cursos</button><button class="suggestion" data-question="¿Cuál es mi próxima clase?"><span aria-hidden="true">▦</span> ¿Cuál es mi próxima clase?</button></div></div><div id="chat-messages" role="log" aria-live="polite" aria-relevant="additions"></div></div></div>
 <footer class="chat-footer"><form id="chat-form"><div class="composer"><textarea id="chat-input" aria-label="Pregunta al asistente" placeholder="Pregunta sobre tus cursos, asistencia o actividades…" rows="2" maxlength="2000"></textarea><div class="composer-tools"><small id="voice-hint">Escribe o pregunta con tu voz</small><div class="composer-buttons"><button type="button" class="chat-cancel" id="voice-cancel" hidden>Cancelar audio</button><button type="button" class="icon-btn" id="chat-mic" aria-label="Preguntar por voz" aria-pressed="false" title="Hablar y consultar al terminar"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg></button><button type="submit" class="send-btn" id="chat-send" aria-label="Enviar pregunta">↑</button></div></div></div><div id="chat-status" class="chat-status" role="status" aria-live="polite"></div><p class="chat-hint">Solo puedes consultar información asociada a tu cuenta.</p></form></footer></section>`;
 document.body.append(host);
 const $=id=>host.querySelector('#'+id);const panel=$('chat-panel'),input=$('chat-input'),status=$('chat-status'),feed=$('chat-feed'),messages=$('chat-messages'),mic=$('chat-mic');
 $('chat-provider').textContent=({ADMIN:'Administrador',PROFESOR:'Profesor',ESTUDIANTE:'Estudiante'})[user.rol]||'Mi cuenta';$('chat-greeting').textContent='Hola, '+user.nombre.split(' ')[0];
 if(user.rol!=='ESTUDIANTE'){const prompts=['Dame un resumen de asistencia','¿Cuántos faltaron hoy?','Ver historial de tardanzas','Muéstrame mis cursos','¿Cuál es mi próxima clase?'];host.querySelectorAll('.suggestion').forEach((b,i)=>{b.dataset.question=prompts[i];b.lastChild.textContent=' '+prompts[i];});}
 for(const [select,items] of [[$('chat-course'),context.courses],[$('chat-student'),context.students]])for(const item of items){const o=document.createElement('option');o.value=item.id;o.textContent=item.nombre;select.append(o);}
 if(user.rol==='ESTUDIANTE'){$('chat-student').hidden=true;$('chat-course').style.width='100%';}
 let backgroundStates=[];
 let busy=false,listening=false,recognition=null,lastFocus=null,cancelled=false,failed=false,finalTranscript='',originalDraft='',historyPromise=null;
 function scroll(){feed.scrollTop=feed.scrollHeight;}
 function add(role,text,meta=''){const row=document.createElement('div');row.className='message '+role;if(role==='assistant'){const avatar=document.createElement('img');avatar.className='chat-avatar chat-message-avatar';avatar.src=avatarUrl;avatar.alt='';row.append(avatar);}const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;if(meta){const small=document.createElement('div');small.className='meta';small.textContent=meta;bubble.append(small);}row.append(bubble);messages.append(row);$('chat-welcome').hidden=true;scroll();return row;}
 function controls(){input.disabled=busy||listening;$('chat-send').disabled=busy||listening;$('chat-new').disabled=busy||listening;mic.disabled=busy;mic.classList.toggle('listening',listening);mic.setAttribute('aria-pressed',String(listening));mic.setAttribute('aria-label',listening?'Terminar audio y consultar':'Preguntar por voz');$('voice-cancel').hidden=!listening;host.querySelectorAll('.suggestion,select').forEach(e=>e.disabled=busy||listening);}
 async function loadHistory(){try{const history=await api('/api/chatbot/history');for(const row of history){add('user',row.question);add('assistant',row.reply);} }catch(e){status.textContent=e.message;} }
 function open(){if(!panel.hidden)return;lastFocus=document.activeElement;panel.hidden=false;$('chat-backdrop').hidden=false;$('chat-launch').setAttribute('aria-expanded','true');backgroundStates=[...document.body.children].filter(el=>el!==host&&!['SCRIPT','STYLE','LINK'].includes(el.tagName)).map(el=>[el,el.inert]);for(const [el] of backgroundStates)el.inert=true;document.body.style.overflow='hidden';if(!historyPromise){historyPromise=loadHistory();}input.focus();}
 function cancelVoice(){if(!listening)return;cancelled=true;recognition.abort();input.value=originalDraft;status.textContent='Audio cancelado. No se envió la pregunta.';}
 function close(){cancelVoice();panel.hidden=true;$('chat-backdrop').hidden=true;$('chat-launch').setAttribute('aria-expanded','false');for(const [el,inert] of backgroundStates)el.inert=inert;backgroundStates=[];document.body.style.overflow='';lastFocus?.focus();}
 $('chat-launch').onclick=open;$('chat-close').onclick=close;$('chat-backdrop').onclick=close;document.querySelectorAll('[data-open-chat]').forEach(b=>b.onclick=open);
 $('chat-expand').onclick=()=>{const expanded=panel.classList.toggle('expanded');$('chat-expand').setAttribute('aria-pressed',String(expanded));$('chat-expand').setAttribute('aria-label',expanded?'Volver al panel lateral':'Expandir pantalla');};
 panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const items=[...panel.querySelectorAll('button,select,textarea')].filter(x=>!x.hidden&&!x.disabled&&x.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 async function send(source='text'){
   if(busy||listening)return;if(historyPromise)await historyPromise;if(busy||listening)return;
   const text=input.value.trim();if(!text)return;if(text.length>2000){status.textContent='La pregunta debe tener hasta 2000 caracteres.';return;}
   busy=true;controls();add('user',text,source==='voice'?'Transcrito desde tu voz':'');input.value='';status.textContent='Consultando tus datos…';const pending=add('assistant','Consultando…');
   const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);
   try{const data=await api('/api/chatbot/message',{method:'POST',signal:controller.signal,body:JSON.stringify({message:text,source,course_id:$('chat-course').value?Number($('chat-course').value):null,student_id:$('chat-student').value?Number($('chat-student').value):null})});pending.remove();add('assistant',data.reply,data.demo?'Datos ficticios · '+data.provider:'Consulta · '+data.provider);status.textContent=data.notice||'';}
   catch(e){pending.remove();add('assistant',e.name==='AbortError'?'La consulta tardó demasiado. Puedes volver a intentarlo.':e.message);input.value=text;status.textContent='Puedes revisar la pregunta y volver a enviarla.';}
   finally{clearTimeout(timer);busy=false;controls();input.focus();}
 }
 $('chat-form').onsubmit=e=>{e.preventDefault();send();};input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send();}});
 host.querySelectorAll('.suggestion').forEach(b=>b.onclick=()=>{input.value=b.dataset.question||b.textContent;send();});
 $('chat-new').onclick=async()=>{if(busy||listening)return;busy=true;controls();try{if(historyPromise)await historyPromise;await api('/api/chatbot/history',{method:'DELETE'});messages.replaceChildren();$('chat-welcome').hidden=false;status.textContent='Nueva conversación.';input.value='';}catch(e){status.textContent=e.message;}finally{busy=false;controls();}};
 const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!Speech){$('voice-hint').textContent='Voz no disponible en este navegador';status.textContent='Este navegador no admite voz; puedes escribir tu pregunta.';mic.disabled=true;mic.title='Este navegador no admite reconocimiento de voz';}else if(!window.isSecureContext){$('voice-hint').textContent='La voz necesita HTTPS o localhost';status.textContent='Para usar el micrófono, abre el sitio con HTTPS o localhost.';mic.disabled=true;}else{
 recognition=new Speech();recognition.lang='es-PE';recognition.continuous=false;recognition.interimResults=true;recognition.maxAlternatives=1;
 recognition.onstart=()=>{status.textContent='Escuchando… Al terminar de hablar se enviará la transcripción.';};
 recognition.onresult=e=>{let interim='';finalTranscript='';for(let i=0;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal)finalTranscript+=text+' ';else interim+=text+' ';}input.value=(finalTranscript+interim).trim();};
 recognition.onerror=e=>{failed=true;const errors={'not-allowed':'Permite el micrófono en el navegador y vuelve a intentarlo.','service-not-allowed':'El servicio de voz no está disponible. Puedes escribir tu pregunta.','no-speech':'No se detectó voz. Inténtalo nuevamente.','audio-capture':'No se encontró un micrófono disponible.','network':'No se pudo conectar con el servicio de voz. Revisa tu conexión.','aborted':'Audio cancelado.'};if(!cancelled)status.textContent=errors[e.error]||'No se pudo transcribir el audio. Puedes escribir tu pregunta.';};
 recognition.onend=()=>{listening=false;controls();if(!cancelled&&!failed&&finalTranscript.trim()){input.value=finalTranscript.trim();status.textContent='Transcripción lista. Enviando consulta…';send('voice');}else if(!cancelled&&!failed){status.textContent='No se obtuvo una transcripción. Puedes volver a intentar.';}input.focus();};
 mic.onclick=()=>{if(busy)return;if(listening){recognition.stop();status.textContent='Terminando transcripción…';return;}cancelled=false;failed=false;finalTranscript='';originalDraft=input.value;listening=true;controls();try{recognition.start();}catch(e){listening=false;controls();status.textContent='No se pudo iniciar el micrófono. Inténtalo nuevamente.';}};
 $('voice-cancel').onclick=cancelVoice;window.addEventListener('pagehide',()=>{cancelled=true;recognition.abort();});
 }
 // Mantiene la desactivación del micrófono en navegadores sin soporte.
 const baseControls=controls;controls=()=>{baseControls();if(!Speech||!window.isSecureContext)mic.disabled=true;};
 window.monitorChat={open,close,setCourse:id=>{$('chat-course').value=String(id);}};
})();
